### ISSUE TITLE
User Subscribed event is missing

### ISSUE THREAD

**Issue by milochristiansen** [pajlada/go-twitch-pubsub#14]
As far as I can tell all the events *except* the `channel-subscribe-events-v1.<channel_id>` event are implemented here.

**Comment by pajlada** [comment]
Do you have the ability to try out the PR to see if it suits your needs @milochristiansen ?
If it works as expected for you, I can make it a release

**Comment by milochristiansen** [comment]
I can at least check if it compiles. I'll need to wait for the next resub to actually test it.

**Comment by milochristiansen** [comment]
Screw it, I gifted my father a sub, and it worked yay

Thank you for still maintaining this :)

**Comment by pajlada** [comment]
Thanks for testing, I'll take a look tomorrow and add some tests

**Comment by pajlada** [comment]
I fixed the issue where the recipient of the gift sub was not included, and added some proper tests for it.
I'll be making a release with this change shortly

**Comment by pajlada** [comment]
It's available in v0.1.0 now
